name: smartling_intl_utils
description: Smartling to intl Utilities

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ^3.0.0
  args: ^2.0.0
  dart_style: ^2.0.0
  http: ^0.13.0
  intl: ^0.18.1
  path: ^1.8.0
  yaml: ^3.0.0
  #intl_utils: ^2.7.0
  intl_utils:
    git:
      url: https://github.com/yongjhih/intl_utils.git
      ref: "5178b92"

dev_dependencies:
  build_runner: ^2.0.6
  mockito: ^5.1.0
  test: ^1.17.10
